;NAME:-SWASTIK BISHOI ,REG.NO:-2341002196(08)

    AREA FACTORIAL ,CODE ,READONLY
	ENTRY
START
    MOV R0,#5;LOAD THE FIRST DATA
	MOV R1,#1; LOAD THE RESULT
FACT_LOOP 
    CMP R0,#0
	BEQ END_LOOP
	MUL R2,R1,R0
	MOV R1,R2
	SUBS R0,R0,#1
	B FACT_LOOP
END_LOOP
    LDR R2,=RESULT
	STR R1,[R2]
EXT B EXT
    AREA RES,DATA,READWRITE
RESULT DCD 0X0
	END